### ISSUE TITLE
Pre-submission to-do list

### ISSUE THREAD

**Issue by slager** [ropensci/DataPackageR#106]
Dave's to-do list:

README
- [x] README.Rmd and README.md need to be checked against each other for conflicts from asynchronous updates
- [x] Update codecov badge URLs
- [x] Rebuild README.md final time

DESCRIPTION
- [x] Update maintainer info and contact info

Docs
- [x] Remove references to "build_package()"

Next
- [ ] Get feedback/decide on trunk + CI model
- [ ] Update spelling
- [ ] Initiate usethis release checklist
- [ ] Add codemetar update
- [ ] CRAN email about unreachable old maintainer email address
- [ ] Cran comments: why pkg got archived and how fixed
